transformer:
  batch_size: 8
  num_epochs: 20
  lr: 0.0001
  seq_len: 319
  d_model: 512
  lang_src: en
  lang_tgt: ur
  model_folder: artifacts/weights
  model_basename: transformer_
  preload: None
  tokenizer_file: artifacts/data/tokenizer_{0}_.json
  experiment_name: artifacts/runs/transformer